### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by BryantN** [JumpingVermillionSushi/TowerDefense#29]
Read How he wants the particle system, kinda different

**Comment by sharpTrick** [comment]
Got this all set up and even made creeps explode.

Still need to: 
Trail on a bomb as it moves
When a bomb hits
Trail behind a guided missile
Explosion when a guided missile hits
When a tower is sold

This should be fairly easy, I pretty much just need to make sure each of these events has a reference to the particle engine, and design the effects.

I'll at least make design these tomorrow.

But to move forward past that I'll need the different projectiles and tower selling.
