### ISSUE TITLE
Polish off base game engine

### ISSUE THREAD

**Issue by sharpTrick** [JumpingVermillionSushi/TowerDefense#6]
This is really mostly the game loop. Bryant knows more about this.

**Comment by BryantN** [comment]
Can help me out By refactoring code to the camel case, add cements to functions, etc...

**Comment by sharpTrick** [comment]
Yes sir, in fact I've added issue #9  to specifically address camel case. @BryantN will you clarify what you may mean by adding cement to functions?

**Comment by BryantN** [comment]
Comments not cement

**Comment by sharpTrick** [comment]
Camel case taken care of by Pull #12, I will work on comments over the weekend.

**Comment by sharpTrick** [comment]
As this issue has been separated and delegated out into issues #13, #10, and #7 I'm going to mark this specific issue as closed.
